version: "3"
services:
  database:
    image: "postgres:alpine3.16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pokemonapiadm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemonapiadmdb